name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Set up build env
      run: cat ./Dockerfile | docker build -t workers-wasi-build -
    - name: Build
      run: docker run --rm -v $(pwd):/workers-wasi workers-wasi-build make -j ci

